#!bin/bash

while true; do
        echo "_______________________________MENU_____________________________"
        echo ""
        echo "________________opc.1 --> Crear un fichero______________________"
        echo "________________opc.2 --> Crear un directorio___________________"
        echo "________________opc.3 --> Borrar un fichero_____________________"
        echo "________________opc.4 --> Borrar un directorio__________________"
        echo ""
        echo ""
        echo "_____________________Me siento afortunado_______________________"
        echo ""
        echo "___________________opc.5 --> Salir del menú_____________________"

        read -p "Por favor, introduce una de las cinco opciones:" $1
        case $1 in
                1)
                        read -p "Cómo se va a llamar el fichero? " $2
                        touch "$2.txt"
                        nano $2.txt
                        ;;
                2)
                       read -p "Cómo se va a llamar el directorio? " $3
                        mkdir "$3"
                        cd /home/adrian/$3
                        ;;
                3)
                        read -p "Qué fichero vas a querer borrar? " $4
                        rm -i "$4"
                        ls
                        ;;
                4)
                        read -p "Qué directorio vas a querer borrar?" $5
                        rmdir $5
                        ls
                        ;;
                5)
                        read -p "Tienes instalados los paquetes necesarios?" $6
                        if [ "$entrada_usuario" = "mi_valor" ]; then
                                echo "Eco"
                        else
                            echo "Hola"
                        fi
                        ;;

        esac
done

